---
- ansible.builtin.import_playbook: machine-hypervisor.yml


# Internet gateway
- ansible.builtin.import_playbook: vm-kickstart.yml
  vars:
    host_to_build: gateway.source.example.com
- ansible.builtin.import_playbook: roles-gateway.yml
- ansible.builtin.import_playbook: machine-to-template.yml
  vars:
    host_to_image: gateway.source.example.com
- ansible.builtin.import_playbook: template-to-machine.yml
  vars:
    host_to_start: gateway.source.example.com


# Red Hat Identity Manager Replica
- ansible.builtin.import_playbook: vm-kickstart.yml
  vars:
    host_to_build: idreplica.source.example.com
- ansible.builtin.import_playbook: roles-idreplica.yml
- ansible.builtin.import_playbook: machine-to-template.yml
  vars:
    host_to_image: idreplica.source.example.com
- ansible.builtin.import_playbook: template-to-machine.yml
  vars:
    host_to_start: idreplica.source.example.com


# Red Hat Satellite Capsule
- ansible.builtin.import_playbook: vm-kickstart.yml
  vars:
    host_to_build: capsule.source.example.com
- ansible.builtin.import_playbook: roles-capsule.yml
- ansible.builtin.import_playbook: machine-to-template.yml
  vars:
    host_to_image: capsule.source.example.com
- ansible.builtin.import_playbook: template-to-machine.yml
  vars:
    host_to_start: capsule.source.example.com


# AAP (Ansible Automation Platform) Execution Environment Node
- ansible.builtin.import_playbook: vm-kickstart.yml
  vars:
    host_to_build: aapee.source.example.com
- ansible.builtin.import_playbook: roles-aapee.yml
- ansible.builtin.import_playbook: machine-to-template.yml
  vars:
    host_to_image: aapee.source.example.com
- ansible.builtin.import_playbook: template-to-machine.yml
  vars:
    host_to_start: aapee.source.example.com


# GitLab
- ansible.builtin.import_playbook: vm-kickstart.yml
  vars:
    host_to_build: git.source.example.com
- ansible.builtin.import_playbook: roles-git.yml
- ansible.builtin.import_playbook: machine-to-template.yml
  vars:
    host_to_image: git.source.example.com
- ansible.builtin.import_playbook: template-to-machine.yml
  vars:
    host_to_start: git.source.example.com


# Hashicorp Vault, CyberArk?
- ansible.builtin.import_playbook: vm-kickstart.yml
  vars:
    host_to_build: secret.source.example.com
- ansible.builtin.import_playbook: roles-secret.yml
- ansible.builtin.import_playbook: machine-to-template.yml
  vars:
    host_to_image: secret.source.example.com
- ansible.builtin.import_playbook: template-to-machine.yml
  vars:
    host_to_start: secret.source.example.com
