- name: Role test
  hosts: git
  become: true
  gather_facts: true
  serial: 1
  vars_files:
    - ~/vault-credentials.yml
  environment:
     http_proxy: "http://gateway.{{ lab_source_domain }}:3128"
     HTTPS_PROXY: "http://gateway.{{ lab_source_domain }}:3128"
     no_proxy: localhost,127.0.0.1,example.com

  roles:
    - role: nick.app.install_gitlab


